version: '3'
services:
  zookeeper:
    image: zookeeper:3.5.7
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/opt/zookeeper-3.5.7/data
    networks:
      - kitchen

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "events:1:1,commands:1:1:compact"
    volumes:
      - kafka:/kafka
    links:
      - zookeeper
    networks:
      - kitchen
  # postgres:
  #   image: postgres:9.5.3
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - kitchen
#   datomic:
# 13:59 $ docker run -it --rm    -p 127.0.0.1:4334-4336:4334-4336    gordonstratton/datomic-free-transactor:latest
networks:
  kitchen:
    external: true
volumes:
  zookeeper:
  kafka:
