version: '3'
services:
  zookeeper:
    image: zookeeper:3.5.7
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/opt/zookeeper-3.5.7/data
    networks:
      - kitchen
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper
    volumes:
      - kafka:/kafka
    networks:
      - kitchen
  # postgres:
  #   image: postgres:9.5.3
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - kitchen
networks:
  kitchen:
    external: true
volumes:
  zookeeper:
  kafka:
